version: "3.3"
services:
  backend:
    container_name: backend
    build: ./backend
    command: sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8080 --reload"
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app

  frontend:
    container_name: frontend
    build: ./frontend
    command: sh -c "npm run start"
    ports:
      - '3000:3000'
    environment:
      - NODE_PATH=/app/node_modules/.bin
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      
