version: "3.3"
services:
  backend: 
    container_name: backend
    build: ./backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:./app

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:./app
      
